'use server';

/**
 * @fileOverview This file defines a Genkit flow for generating a professional summary for a resume.
 *
 * - generateProfessionalSummary - A function that generates a professional summary based on user inputs.
 * - GenerateProfessionalSummaryInput - The input type for the generateProfessionalSummary function.
 * - GenerateProfessionalSummaryOutput - The return type for the generateProfessionalSummary function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateProfessionalSummaryInputSchema = z.object({
  skills: z.string().describe('A comma-separated list of skills.'),
  workExperience: z.string().describe('A description of work experience.'),
  education: z.string().describe('A description of education.'),
});
export type GenerateProfessionalSummaryInput = z.infer<
  typeof GenerateProfessionalSummaryInputSchema
>;

const GenerateProfessionalSummaryOutputSchema = z.object({
  summary: z.string().describe('A professional summary generated by AI.'),
});
export type GenerateProfessionalSummaryOutput = z.infer<
  typeof GenerateProfessionalSummaryOutputSchema
>;

export async function generateProfessionalSummary(
  input: GenerateProfessionalSummaryInput
): Promise<GenerateProfessionalSummaryOutput> {
  return generateProfessionalSummaryFlow(input);
}

const prompt = ai.definePrompt({
  name: 'generateProfessionalSummaryPrompt',
  input: {schema: GenerateProfessionalSummaryInputSchema},
  output: {schema: GenerateProfessionalSummaryOutputSchema},
  prompt: `You are a resume expert. Generate a professional summary for a resume based on the following information. The summary should be concise, highlight key skills and experiences, and be tailored for Applicant Tracking Systems (ATS). Use industry-relevant keywords.

Skills: {{{skills}}}
Work Experience: {{{workExperience}}}
Education: {{{education}}}`,
});

const generateProfessionalSummaryFlow = ai.defineFlow(
  {
    name: 'generateProfessionalSummaryFlow',
    inputSchema: GenerateProfessionalSummaryInputSchema,
    outputSchema: GenerateProfessionalSummaryOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
